import { useNavigate } from "react-router-dom";

export default function Terms() {
  const navigate = useNavigate();
  const token = localStorage.getItem("token");
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-10">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-slate-600 hover:text-blue-600 transition cursor-pointer"
          >
            <span className="text-xl">←</span>
            <span>Back to {token ? "Dashboard" : "Home"}</span>
          </button>
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          Terms & Conditions{" "}
        </h1>
        <p className="text-sm text-gray-500 mb-8">
          Last updated: September 2026
        </p>
        <div className="space-y-8 text-gray-700 leading-7">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using PrepPilot, you agree to be bound by these
              Terms & Conditions. If you do not agree with these terms, please
              do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              2. About PrepPilot
            </h2>
            <p>
              PrepPilot is an AI-powered interview preparation platform designed
              to help users practice interviews, receive feedback, and improve
              their interview skills.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              3. User Accounts
            </h2>
            <p>
              You are responsible for providing accurate information when
              creating an account and for maintaining the security of your
              account credentials. You are responsible for all activity
              performed through your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              4. Resume and User Content
            </h2>
            <p>
              Users may upload resumes and other information to use PrepPilot's
              features. You retain responsibility for the content you upload and
              must ensure that you have the right to provide such content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              5. AI-Generated Content
            </h2>
            <p>
              PrepPilot uses artificial intelligence to generate interview
              questions, evaluations, feedback, and other content. AI-generated
              results are intended for practice and educational purposes and may
              not always be accurate or complete.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              6. Acceptable Use
            </h2>
            <p>
              You agree not to misuse PrepPilot, attempt to gain unauthorized
              access to the platform, interfere with its operation, or use the
              service for unlawful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              7. Intellectual Property
            </h2>
            <p>
              The PrepPilot platform, including its design, software, branding,
              and original content, is protected by applicable intellectual
              property laws. You may not copy, modify, distribute, or reproduce
              these materials without permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              8. Service Availability
            </h2>
            <p>
              We may modify, suspend, or discontinue features of PrepPilot from
              time to time. We do not guarantee that the platform will always be
              available or uninterrupted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              9. Limitation of Liability
            </h2>
            <p>
              PrepPilot is provided for interview preparation and educational
              purposes. We are not responsible for decisions made based solely
              on information, feedback, or results generated by the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              10. Changes to These Terms
            </h2>
            <p>
              We may update these Terms & Conditions from time to time. Updated
              terms will be posted on this page with a revised effective date.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              11. Contact
            </h2>
            <p>
              If you have questions about our policies, please contact us at{" "}
              <a
                href="mailto:preppilot.support@gmail.com"
                className="text-blue-600 hover:underline"
              >
                preppilot.support@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
